[package]
name = "prose_dl"
version = "0.3.1"
edition = "2021"
license = "AGPL-3.0-or-later"

[dependencies]
clap = { version = "4.0.17", features = ["derive"] }
reqwest = { version = "0.11" }
tokio = { version = ">=1.23.1", features = ["full"] }
scraper = "0.14"
