[package]
name = "prose_dl"
version = "0.3.1"
edition = "2021"

[dependencies]
clap = { version = "4.0.17", features = ["derive"] }
reqwest = { version = "0.11" }
tokio = { version = ">=1.13.1", features = ["full"] }
scraper = "0.13"
